language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: PegJm4Vwc8uSfPOZOe31vI40fEohOjIF+uo4boMl2bUN2ySW4YiFuVOUIuMv66e4QBAsz3MlvGwavNJbC7rFoHpdvvd4BxDkbNG8eTkMIXUgB7uWWf8c5Cp8KAVfgtpzE6cUJraiNoxdghFOU8LqG+aDyR/M+4JO38PoE2zfyPu+vuuCzPPDuWTbCyQUw2FQohDUGhGfMO0cm6/Z/kEnFSOPSNky5vnTQlUnL6MedPvd79jFjRW3kzPxYBHXbHUsg3UcKaaWMHuyCdbf9vS5bbDMHgOAe78LJIVB08gyv8mvdT4sd/CcBtfbl1tqFPuuKPx06UvkLnLC1sZv7Td9zQVMTmK3MdEKmqzZlGsAhdVQuoCSa2REKkNjr5w2UyTdwiN8Tbg3xWk3p0R45PiXiSb7rvc09CVwmGu/w/t7jtLYmbFD3jCqxqgo9ZYarwUhBxl0fpaO3Z6JfigxKC3KdzOv2dNF9hnZy+uigmxPXgEdSnn7HKA4yo2WnnN4XKsLlSwebvbLKcdPHj+P26fEw40nSHMR+w2l5awm34ZgRjLv6Npg0FmCPTJrEcS501mshZtvPhKy07e/zoCyJ8g8JXjMpSqn3bLuDwoOjRwGgmigatjMRfIXNmUvEtsdO7wXp6V/SHAx+ucZi9FvXi9wQ5f9uzK7t+1hhVKek2QHAR8=
